development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: db_dev
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: db_test
  pool: 5
  username: postgres
  password: postgres